services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s

  api:
    build:
      context: .
      dockerfile: src/FinanceTracker.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - Keycloak__AdminUser=${KEYCLOAK_USER}
      - Keycloak__AdminPassword=${KEYCLOAK_PASSWORD}
    ports:
      - "${API_PORT}:8080"
    volumes:
      - ./logs:/app/logs
    depends_on:
      migration_tool:
        condition: service_completed_successfully

  migration_tool:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    volumes:
      - ./src:/src
      - /src/FinanceTracker.Api/bin
      - /src/FinanceTracker.Api/obj
      - /src/FinanceTracker.Infrastructure/bin
      - /src/FinanceTracker.Infrastructure/obj
      - /src/FinanceTracker.Application/bin
      - /src/FinanceTracker.Application/obj
      - /src/FinanceTracker.Domain/bin
      - /src/FinanceTracker.Domain/obj
    working_dir: /src
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - Jwt__Key=${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    entrypoint: >
      sh -c "dotnet tool install --global dotnet-ef || true &&
             export PATH=\"$$PATH:/root/.dotnet/tools\" &&
             dotnet restore FinanceTracker.sln &&
             count=0 &&
             until dotnet ef database update --project FinanceTracker.Infrastructure/FinanceTracker.Infrastructure.csproj --startup-project FinanceTracker.Api/FinanceTracker.Api.csproj || [ $$count -eq 60 ]; do
               echo 'Database is not ready, try: $$count, retrying in 5s...'
               sleep 5
               count=$$((count+1))
             done && 
             if [ $$count -eq 60 ]; then echo 'Database did not start in time!'; exit 1; fi"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    command: start-dev --import-realm
    environment:
      KC_HTTP_PORT: 8080
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8081
      KC_HTTP_ENABLED: "true"
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - "8081:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/finance-tracker-realm.json:/opt/keycloak/data/import/finance-tracker-realm.json

volumes:
  db_data:
  keycloak_data:
